from . import  wizard_goods
from . import  wizard_financial
from . import  wizard_sale
from . import wizard_end_of_day
from . import wizard_revenue
from . import wizard_employees
from . import wizard_partner
from . import wizard_reward_point
from . import wizard_reward_point_history